name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: main repo
        uses: actions/checkout@v2
        with:
          repository: ''
      - name: list repo'
        run: ls -R
      - name: clone another repo
        uses: actions/checkout@v2
        with:
          repository: pervezalam777/webhook-connect-one
          path: webhook-connect-one
      - name: create translation branch
        run: |
          cd webhook-connect-one
          /usr/bin/git checkout -b translation
      - name: copy translations file
        run: cp -r ./public ./webhook-connect-one/public
      - name: commit and push changes in webhook-connect-one
        run: |
          cd webhook-connect-one
          /usr/bin/git config --local --name-only --get-regexp core\.sshCommand
          /usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
          /usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
          /usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
          /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
          /usr/bin/git add .
          /usr/bin/git commit -m "translations added"
          /usr/bin/git push --set-upstream origin translation
      - name: list
        run: ls -R
          
