name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: main repo
        uses: actions/checkout@v2
        with:
          repository: ''
      - name: list repo'
        run: ls -R
      - name: clone another repo
        uses: actions/checkout@v2
        with:
          repository: pervezalam777/webhook-connect-one
          path: webhook-connect-one
      - name: create translation branch
        run: |
          cd webhook-connect-one
          /usr/bin/git checkout -b translation
      - name: list
        run: ls -R
          
