name: CI

on:
  push:
    branches: [ master ]
env: 
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: main repo
        run: |
          mkdir $GITHUB_REPOSITORY
          cd $GITHUB_REPOSITORY
          /usr/bin/git init
          /usr/bin/git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          /usr/bin/git pull
          cd ..
      - name: list repo'
        run: ls -R
      - name: clone another repo
        run: |
          mkdir webhook-connect-one
          cd webhook-connect-one
          /usr/bin/git init
          /usr/bin/git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/webhook-connect-one.git"
          /usr/bin/git pull
          /usr/bin/git checkout -b translation  
          cd ..
          cp -r ./$GITHUB_REPOSITORY/public ./webhook-connect-one/public
          cd webhook-connect-one
          /usr/bin/git add .
          /usr/bin/git commit -m "translations added"
          /usr/bin/git push --set-upstream origin translation
      - name: list
        run: ls -R
          
