name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: source repo
        run: |
          /usr/bin/git clone "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
      - name: destination repo one
        run: |      
          /usr/bin/git clone "https://$GITHUB_ACTOR:${{ secrets.API_TOKEN_GITHUB }}@github.com/$GITHUB_ACTOR/webhook-connect-one.git"
          cd webhook-connect-one
          /usr/bin/git config --global user.email "action.bot@github.com"
          /usr/bin/git config --global user.name  "action bot"
          /usr/bin/git checkout -b translation
          cd ..
          cp -r ./github-action-main/public ./webhook-connect-one
          cd webhook-connect-one
          /usr/bin/git add .
          /usr/bin/git commit -m "translations added"
          /usr/bin/git push --set-upstream origin translation
