# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: 'list repo'
        run: ls -R
      # Runs a set of commands using the runners shell
      - name: create directory and change to directory
        run: |
          mkdir -p test-repo and
          cd test-repo
      - name: clone another repo
        uses: actions/checkout@master
        with:
          repository: pervezalam777/webhook-connect-one
      - name: create an branch
        run: git checkout -b translation
      - name: come back to root
        run: cd ..
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: public
          target: webhook-connect-one/public
      - name: list
        run: ls -R
          
