name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: main repo
        run: |
          /usr/bin/git clone "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
      - name: list repo'
        run: ls -R
      - name: clone another repo
        run: |      
          /usr/bin/git clone "https://$GITHUB_ACTOR:${{ secrets.API_TOKEN_GITHUB }}@github.com/$GITHUB_ACTOR/webhook-connect-one.git"
          cd webhook-connect-one
          /usr/bin/git config --global user.email "pervezalam777@gmail.com"
          /usr/bin/git config --global user.name  "pervezalam777"
          /usr/bin/git checkout -b translation
          cd ..
          ls -l
          cat ./github-action-main/public/locales/en_in/translation.json
          cp -r ./github-action-main/public ./webhook-connect-one
          cd webhook-connect-one
          ls -R
          cat ./public/locales/en_in/translation.json
          /usr/bin/git add .
          /usr/bin/git commit -m "translations added"
          /usr/bin/git push --set-upstream origin translation
    #  - name: Create Pull Request
    #    id: cpr
    #    uses: peter-evans/create-pull-request@v3
    #    with:
    #      token: ${{ secrets.API_TOKEN_GITHUB }}
    #      path: ./webhook-connect-one
    #      commit-message: Update translation
    #      committer: GitHub <noreply@github.com>
    #      author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
    #      title: '[Test] Update translation'
    #      base: master
    #      branch: translation
